remove superlu since failing due to issue with 'complex'

diff --git a/ossetup b/ossetup
--- a/ossetup
+++ b/ossetup
@@ -23,5 +23,6 @@ elif [ "$RUNNER_OS" == "macOS" ]; then
   brew update
   brew install python@3.10 || true
   brew install python@3.11 || true
-  brew install openmpi superlu suite-sparse gmsh boost pkg-config || true
+  brew install openmpi suite-sparse gmsh boost pkg-config || true
+  # + superlu (is failing currently)
 fi
