improve tests of different branch

diff --git a/package b/package
--- a/package
+++ b/package
@@ -23,3 +23,35 @@ package()
     $packaging --onlysdist --version=$tag
   fi
 }
+
+clonemodule()
+{
+  m=$1 # module name
+  p=$2 # path to module (part after https://gitlab.dune-project.org/)
+  v=$3 # version tag to check if available on pypi
+  t=$4 # tag/branch to try to clone into - master used if not available
+  echo "cloning called with $m $p $v $t into $PWD"
+  # test if package with this version is already uploaded to pypi
+  # if it is no new package will be build and the pypi package is used
+  if ! python3 ../testpypi.py $m $v ; then
+      echo "Try cloning from $p branch $t"
+      git clone --depth 1 -b $t https://gitlab.dune-project.org/$p > /dev/null 2>&1
+      if [ ! $? = 0 ]; then # the branch/tag didn't exist so use master
+        if [ ! $upload = "none" ]; then
+          echo "required branch $t not found in $m - this inconsistent state should not be uploaded."
+          echo "Rerun test with 'upload=none'."
+          exit 1
+        fi
+        echo "using master since $t branch not found!"
+        git clone --depth 1 https://gitlab.dune-project.org/$p > /dev/null 2>&1
+      fi
+      cd $m
+      git log | head
+      package $base
+      cd ..
+  else
+      echo "module with this version found on $upload - using that instead of cloning"
+  fi
+}
+
+
